namespace dissertationProj.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class BreakingDownRisks : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.Patients", "bmi", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.Patients", "preExistingFactors_parity_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_parity_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_parity_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_previousVTE_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_previousVTE_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_previousVTE_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_surgeryVTE_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_surgeryVTE_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_surgeryVTE_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_highRiskThrombophilia_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_highRiskThrombophilia_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_highRiskThrombophilia_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_cancer_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_cancer_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_cancer_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_heartFailure_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_heartFailure_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_heartFailure_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_activeSystemicLupusErythematosus_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_activeSystemicLupusErythematosus_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_activeSystemicLupusErythematosus_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_inflammatoryPolyarthropathy_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_inflammatoryPolyarthropathy_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_inflammatoryPolyarthropathy_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_inflammatoryBowelDisease_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_inflammatoryBowelDisease_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_inflammatoryBowelDisease_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_nephroticSyndrome_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_nephroticSyndrome_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_nephroticSyndrome_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_typeIDiabetesMellitusWithNephropathy_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_typeIDiabetesMellitusWithNephropathy_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_typeIDiabetesMellitusWithNephropathy_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_sickleCellDisease_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_sickleCellDisease_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_sickleCellDisease_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_currentIntravenousDrugUser_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_currentIntravenousDrugUser_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_currentIntravenousDrugUser_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_familyHistoryVTEFirstDegreeRelative_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_familyHistoryVTEFirstDegreeRelative_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_familyHistoryVTEFirstDegreeRelative_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_lowRiskThrombophilia_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_lowRiskThrombophilia_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_lowRiskThrombophilia_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_smoker_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_smoker_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_smoker_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_grossVaricoseVeins_riskName", c => c.String());
            AddColumn("dbo.Patients", "preExistingFactors_grossVaricoseVeins_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "preExistingFactors_grossVaricoseVeins_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_preEclampsiaInCurrentPregnancy_riskName", c => c.String());
            AddColumn("dbo.Patients", "ObstetricFactors_preEclampsiaInCurrentPregnancy_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_preEclampsiaInCurrentPregnancy_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_ARTorIVF_riskName", c => c.String());
            AddColumn("dbo.Patients", "ObstetricFactors_ARTorIVF_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_ARTorIVF_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_multiplePregnancy_riskName", c => c.String());
            AddColumn("dbo.Patients", "ObstetricFactors_multiplePregnancy_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_multiplePregnancy_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_caesareanSectionInLabour_riskName", c => c.String());
            AddColumn("dbo.Patients", "ObstetricFactors_caesareanSectionInLabour_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_caesareanSectionInLabour_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_electiveCaesareanSection_riskName", c => c.String());
            AddColumn("dbo.Patients", "ObstetricFactors_electiveCaesareanSection_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_electiveCaesareanSection_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_operativeDelivery_riskName", c => c.String());
            AddColumn("dbo.Patients", "ObstetricFactors_operativeDelivery_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_operativeDelivery_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_prolongedLabour_riskName", c => c.String());
            AddColumn("dbo.Patients", "ObstetricFactors_prolongedLabour_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_prolongedLabour_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_PPH_riskName", c => c.String());
            AddColumn("dbo.Patients", "ObstetricFactors_PPH_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_PPH_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_pretermBirth_riskName", c => c.String());
            AddColumn("dbo.Patients", "ObstetricFactors_pretermBirth_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_pretermBirth_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_stillBirth_riskName", c => c.String());
            AddColumn("dbo.Patients", "ObstetricFactors_stillBirth_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "ObstetricFactors_stillBirth_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "TransientFactors_surgicalProcedure_riskName", c => c.String());
            AddColumn("dbo.Patients", "TransientFactors_surgicalProcedure_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "TransientFactors_surgicalProcedure_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "TransientFactors_Hyperemesis_riskName", c => c.String());
            AddColumn("dbo.Patients", "TransientFactors_Hyperemesis_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "TransientFactors_Hyperemesis_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "TransientFactors_OHSS_riskName", c => c.String());
            AddColumn("dbo.Patients", "TransientFactors_OHSS_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "TransientFactors_OHSS_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "TransientFactors_currentSystemicInfection_riskName", c => c.String());
            AddColumn("dbo.Patients", "TransientFactors_currentSystemicInfection_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "TransientFactors_currentSystemicInfection_riskSelected", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "TransientFactors_immobilityOrDehydration_riskName", c => c.String());
            AddColumn("dbo.Patients", "TransientFactors_immobilityOrDehydration_riskValue", c => c.Int(nullable: false));
            AddColumn("dbo.Patients", "TransientFactors_immobilityOrDehydration_riskSelected", c => c.Boolean(nullable: false));
            DropColumn("dbo.Patients", "parity");
            DropColumn("dbo.Patients", "previousVTE");
            DropColumn("dbo.Patients", "surgeryVTE");
            DropColumn("dbo.Patients", "highRiskThrombophilia");
            DropColumn("dbo.Patients", "cancer");
            DropColumn("dbo.Patients", "heartFailure");
            DropColumn("dbo.Patients", "activeSystemicLupusErythematosus");
            DropColumn("dbo.Patients", "inflammatoryPolyarthropathy");
            DropColumn("dbo.Patients", "inflammatoryBowelDisease");
            DropColumn("dbo.Patients", "nephroticSyndrome");
            DropColumn("dbo.Patients", "typeIDiabetesMellitusWithNephropathy");
            DropColumn("dbo.Patients", "sickleCellDisease");
            DropColumn("dbo.Patients", "currentInratvenousDrugUser");
            DropColumn("dbo.Patients", "familyHistoryVTEFirstDegreeRelative");
            DropColumn("dbo.Patients", "lowRiskThrombophilia");
            DropColumn("dbo.Patients", "smoker");
            DropColumn("dbo.Patients", "grossVaricoseVeins");
            DropColumn("dbo.Patients", "obesity");
            DropColumn("dbo.Patients", "preEclampsiaInCurrentPregnancy");
            DropColumn("dbo.Patients", "ARTorIVF");
            DropColumn("dbo.Patients", "multiplePregnancy");
            DropColumn("dbo.Patients", "caesareanSectionInLabour");
            DropColumn("dbo.Patients", "electiveCaesareanSection");
            DropColumn("dbo.Patients", "operativeDelivery");
            DropColumn("dbo.Patients", "prolongedLabour");
            DropColumn("dbo.Patients", "PPH");
            DropColumn("dbo.Patients", "pretermBirth");
            DropColumn("dbo.Patients", "stillBirth");
            DropColumn("dbo.Patients", "surgicalProcedure");
            DropColumn("dbo.Patients", "Hyperemesis");
            DropColumn("dbo.Patients", "OHSS");
            DropColumn("dbo.Patients", "currentSystemicInfection");
            DropColumn("dbo.Patients", "immobilityOrDehydration");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Patients", "immobilityOrDehydration", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "currentSystemicInfection", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "OHSS", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "Hyperemesis", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "surgicalProcedure", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "stillBirth", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "pretermBirth", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "PPH", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "prolongedLabour", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "operativeDelivery", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "electiveCaesareanSection", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "caesareanSectionInLabour", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "multiplePregnancy", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "ARTorIVF", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "preEclampsiaInCurrentPregnancy", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "obesity", c => c.String());
            AddColumn("dbo.Patients", "grossVaricoseVeins", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "smoker", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "lowRiskThrombophilia", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "familyHistoryVTEFirstDegreeRelative", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "currentInratvenousDrugUser", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "sickleCellDisease", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "typeIDiabetesMellitusWithNephropathy", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "nephroticSyndrome", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "inflammatoryBowelDisease", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "inflammatoryPolyarthropathy", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "activeSystemicLupusErythematosus", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "heartFailure", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "cancer", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "highRiskThrombophilia", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "surgeryVTE", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "previousVTE", c => c.Boolean(nullable: false));
            AddColumn("dbo.Patients", "parity", c => c.Int(nullable: false));
            DropColumn("dbo.Patients", "TransientFactors_immobilityOrDehydration_riskSelected");
            DropColumn("dbo.Patients", "TransientFactors_immobilityOrDehydration_riskValue");
            DropColumn("dbo.Patients", "TransientFactors_immobilityOrDehydration_riskName");
            DropColumn("dbo.Patients", "TransientFactors_currentSystemicInfection_riskSelected");
            DropColumn("dbo.Patients", "TransientFactors_currentSystemicInfection_riskValue");
            DropColumn("dbo.Patients", "TransientFactors_currentSystemicInfection_riskName");
            DropColumn("dbo.Patients", "TransientFactors_OHSS_riskSelected");
            DropColumn("dbo.Patients", "TransientFactors_OHSS_riskValue");
            DropColumn("dbo.Patients", "TransientFactors_OHSS_riskName");
            DropColumn("dbo.Patients", "TransientFactors_Hyperemesis_riskSelected");
            DropColumn("dbo.Patients", "TransientFactors_Hyperemesis_riskValue");
            DropColumn("dbo.Patients", "TransientFactors_Hyperemesis_riskName");
            DropColumn("dbo.Patients", "TransientFactors_surgicalProcedure_riskSelected");
            DropColumn("dbo.Patients", "TransientFactors_surgicalProcedure_riskValue");
            DropColumn("dbo.Patients", "TransientFactors_surgicalProcedure_riskName");
            DropColumn("dbo.Patients", "ObstetricFactors_stillBirth_riskSelected");
            DropColumn("dbo.Patients", "ObstetricFactors_stillBirth_riskValue");
            DropColumn("dbo.Patients", "ObstetricFactors_stillBirth_riskName");
            DropColumn("dbo.Patients", "ObstetricFactors_pretermBirth_riskSelected");
            DropColumn("dbo.Patients", "ObstetricFactors_pretermBirth_riskValue");
            DropColumn("dbo.Patients", "ObstetricFactors_pretermBirth_riskName");
            DropColumn("dbo.Patients", "ObstetricFactors_PPH_riskSelected");
            DropColumn("dbo.Patients", "ObstetricFactors_PPH_riskValue");
            DropColumn("dbo.Patients", "ObstetricFactors_PPH_riskName");
            DropColumn("dbo.Patients", "ObstetricFactors_prolongedLabour_riskSelected");
            DropColumn("dbo.Patients", "ObstetricFactors_prolongedLabour_riskValue");
            DropColumn("dbo.Patients", "ObstetricFactors_prolongedLabour_riskName");
            DropColumn("dbo.Patients", "ObstetricFactors_operativeDelivery_riskSelected");
            DropColumn("dbo.Patients", "ObstetricFactors_operativeDelivery_riskValue");
            DropColumn("dbo.Patients", "ObstetricFactors_operativeDelivery_riskName");
            DropColumn("dbo.Patients", "ObstetricFactors_electiveCaesareanSection_riskSelected");
            DropColumn("dbo.Patients", "ObstetricFactors_electiveCaesareanSection_riskValue");
            DropColumn("dbo.Patients", "ObstetricFactors_electiveCaesareanSection_riskName");
            DropColumn("dbo.Patients", "ObstetricFactors_caesareanSectionInLabour_riskSelected");
            DropColumn("dbo.Patients", "ObstetricFactors_caesareanSectionInLabour_riskValue");
            DropColumn("dbo.Patients", "ObstetricFactors_caesareanSectionInLabour_riskName");
            DropColumn("dbo.Patients", "ObstetricFactors_multiplePregnancy_riskSelected");
            DropColumn("dbo.Patients", "ObstetricFactors_multiplePregnancy_riskValue");
            DropColumn("dbo.Patients", "ObstetricFactors_multiplePregnancy_riskName");
            DropColumn("dbo.Patients", "ObstetricFactors_ARTorIVF_riskSelected");
            DropColumn("dbo.Patients", "ObstetricFactors_ARTorIVF_riskValue");
            DropColumn("dbo.Patients", "ObstetricFactors_ARTorIVF_riskName");
            DropColumn("dbo.Patients", "ObstetricFactors_preEclampsiaInCurrentPregnancy_riskSelected");
            DropColumn("dbo.Patients", "ObstetricFactors_preEclampsiaInCurrentPregnancy_riskValue");
            DropColumn("dbo.Patients", "ObstetricFactors_preEclampsiaInCurrentPregnancy_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_grossVaricoseVeins_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_grossVaricoseVeins_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_grossVaricoseVeins_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_smoker_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_smoker_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_smoker_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_lowRiskThrombophilia_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_lowRiskThrombophilia_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_lowRiskThrombophilia_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_familyHistoryVTEFirstDegreeRelative_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_familyHistoryVTEFirstDegreeRelative_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_familyHistoryVTEFirstDegreeRelative_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_currentIntravenousDrugUser_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_currentIntravenousDrugUser_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_currentIntravenousDrugUser_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_sickleCellDisease_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_sickleCellDisease_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_sickleCellDisease_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_typeIDiabetesMellitusWithNephropathy_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_typeIDiabetesMellitusWithNephropathy_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_typeIDiabetesMellitusWithNephropathy_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_nephroticSyndrome_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_nephroticSyndrome_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_nephroticSyndrome_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_inflammatoryBowelDisease_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_inflammatoryBowelDisease_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_inflammatoryBowelDisease_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_inflammatoryPolyarthropathy_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_inflammatoryPolyarthropathy_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_inflammatoryPolyarthropathy_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_activeSystemicLupusErythematosus_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_activeSystemicLupusErythematosus_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_activeSystemicLupusErythematosus_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_heartFailure_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_heartFailure_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_heartFailure_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_cancer_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_cancer_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_cancer_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_highRiskThrombophilia_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_highRiskThrombophilia_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_highRiskThrombophilia_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_surgeryVTE_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_surgeryVTE_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_surgeryVTE_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_previousVTE_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_previousVTE_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_previousVTE_riskName");
            DropColumn("dbo.Patients", "preExistingFactors_parity_riskSelected");
            DropColumn("dbo.Patients", "preExistingFactors_parity_riskValue");
            DropColumn("dbo.Patients", "preExistingFactors_parity_riskName");
            DropColumn("dbo.Patients", "bmi");
        }
    }
}
